spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
  datasource:
    generate-unique-name: false
    name: java-challenge-db
  h2.console.enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8888

logging:
  level:
    org.springframework: INFO
    org.springframework.cache: TRACE